/*=auto=========================================================================
(c) Copyright 2003 Massachusetts Institute of Technology (MIT) All Rights Reserved.

This software ("3D Slicer") is provided by The Brigham and Women's 
Hospital, Inc. on behalf of the copyright holders and contributors.
Permission is hereby granted, without payment, to copy, modify, display 
and distribute this software and its documentation, if any, for  
research purposes only, provided that (1) the above copyright notice and 
the following four paragraphs appear on all copies of this software, and 
(2) that source code to any modifications to this software be made 
publicly available under terms no more restrictive than those in this 
License Agreement. Use of this software constitutes acceptance of these 
terms and conditions.

3D Slicer Software has not been reviewed or approved by the Food and 
Drug Administration, and is for non-clinical, IRB-approved Research Use 
Only.  In no event shall data or images generated through the use of 3D 
Slicer Software be used in the provision of patient care.

IN NO EVENT SHALL THE COPYRIGHT HOLDERS AND CONTRIBUTORS BE LIABLE TO 
ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL 
DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, 
EVEN IF THE COPYRIGHT HOLDERS AND CONTRIBUTORS HAVE BEEN ADVISED OF THE 
POSSIBILITY OF SUCH DAMAGE.

THE COPYRIGHT HOLDERS AND CONTRIBUTORS SPECIFICALLY DISCLAIM ANY EXPRESS 
OR IMPLIED WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND 
NON-INFRINGEMENT.

THE SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS 
IS." THE COPYRIGHT HOLDERS AND CONTRIBUTORS HAVE NO OBLIGATION TO 
PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.

=========================================================================auto=*/
#ifndef __KLRegistration_h
#define __KLRegistration_h
// .NAME KLRegistration - uses KL Distance to Register 2 images 
// .SECTION Description
// KLRegistration computes a transformation that will align
// the source image with the target image. It does this according
// to a histogram generated by already aligned images.
//
//
// It uses the ITK registration framework with
// the following combination of components:
//   - KLHistogramImageToImageMetric
//   - QuaternionRigidTransform
//   - QuaternionRigidTransformGradientDescentOptimizer
//   - LinearInterpolateImageFunction
// 
// The registration is done using a multiresolution strategy.
// At each resolution level, the downsampled images are obtained
// using a RecursiveMultiResolutionPyramidImageFilter.
// 
// Note that this class requires both images to be 3D and with
// pixels of a real type.
// 
// The registration process is activated by method Execute().
// 
// Inputs:
//   - pointer to fixed image
//   - pointer to moving image
//   - number of resolution levels
//   - scaling applied to the translation parameters during optimization
//   - parzen window width for the fixed image
//   - parzen window width for the moving image
//   - number of optimization iterations at each level
//   - the optimization learning rate at each level
//   - the initial rigid (quaternion) transform parameters
//   - the coarest level shrink factors for the fixed image
//   - the coarest level shrink factors for the moving image
// 
// Outputs:
//   - rigid (quaternion) transform parameters to maps points from
//     the fixed image to the moving image.
//   - pointer to equivalent affine transform.
//
//
// .SECTION Thanks
// Thanks to Samson Timoner who created this class.

#include "itkObject.h"
#include "itkMultiResolutionImageRegistrationMethod.h"

#include "itkQuaternionRigidTransform.h"
#include "itkAffineTransform.h"
#include "itkKLHistogramImageToImageMetric.h"
#include "itkLinearInterpolateImageFunction.h"
#include "itkQuaternionRigidTransformGradientDescentOptimizerModified.h"
#include "itkRecursiveMultiResolutionPyramidImageFilter.h"

#include "itkArray.h"

class vtkMatrix4x4;

#include "vtkRigidIntensityRegistrationConfigure.h"

namespace itk
{

template <typename TFixedImage, typename TMovingImage>
class KLRegistration : public Object
{
public:

  /** Standard class typedefs. */
  typedef KLRegistration Self;
  typedef Object Superclass;
  typedef SmartPointer<Self> Pointer;
  typedef SmartPointer<const Self>  ConstPointer;

  /** Run-time type information (and related methods). */
  itkTypeMacro(KLRegistration, Object);

  /** Method for creation through the object factory. */
  itkNewMacro(Self);

  // ----------------------------------------------------------------------
  // All the Type Definitions
  // ----------------------------------------------------------------------

  /** Fixed Image Type. */
  typedef TFixedImage FixedImageType;

  /** Moving Image Type. */
  typedef TMovingImage MovingImageType;

  /** Image dimension enumeration. */
  itkStaticConstMacro (ImageDimension, unsigned int, TFixedImage::ImageDimension);

  /** Transform Type. */
  typedef AffineTransform< double, 3 >       AffineTransformType;
  typedef QuaternionRigidTransform< double >       TransformType;

  /** Optimizer Type. */
  typedef QuaternionRigidTransformGradientDescentOptimizerModified 
                                                         OptimizerType;

  /** Metric Type. */
  typedef KLHistogramImageToImageMetric< 
                                    FixedImageType, 
                                    MovingImageType >    MetricType;

  /** Interpolation Type. */
  typedef LinearInterpolateImageFunction< 
                                    MovingImageType,
                                    double          >    InterpolatorType;

  /** Fixed Image Pyramid Type. */
  typedef RecursiveMultiResolutionPyramidImageFilter<
                                    FixedImageType,
                                    FixedImageType  >    FixedImagePyramidType;

  /** Moving Image Pyramid Type. */
  typedef RecursiveMultiResolutionPyramidImageFilter<
                                    MovingImageType,
                                    MovingImageType  >   MovingImagePyramidType;

  /** Registration Method. */
  typedef MultiResolutionImageRegistrationMethod< 
                                    FixedImageType, 
                                    MovingImageType >    RegistrationType;

  /** Transform parameters type. */
  typedef typename RegistrationType::ParametersType     ParametersType;

  /** DoubleArray type. */
  typedef Array<double>  DoubleArray;

  /** UnsignedIntArray type. */
   typedef Array<unsigned int> UnsignedIntArray;

  /** ShrinkFactorsArray type. */
  typedef FixedArray<unsigned int,itkGetStaticConstMacro(ImageDimension)> ShrinkFactorsArray;

  // ----------------------------------------------------------------------
  // Set the Parameters for the Registration
  // ----------------------------------------------------------------------

  /** Set the fixed image. */
  itkSetObjectMacro( FixedImage, FixedImageType );

  /** Get the fixed image. */
  itkGetObjectMacro( FixedImage, FixedImageType );

  /** Set the moving image. */
  itkSetObjectMacro( MovingImage, MovingImageType );

  /** Get the moving image. */
  itkGetObjectMacro( MovingImage, MovingImageType );

  /** Set the number of resolution levels. */
  itkSetClampMacro( NumberOfLevels, unsigned short, 1,
    NumericTraits<unsigned short>::max() );

  /** Set the translation parameter scales. */
  itkSetClampMacro( TranslationScale, double, 0.0,
    NumericTraits<double>::max() );

  /** Set the image parzen window widths. */
  itkSetClampMacro( MovingImageStandardDeviation, double, 0.0,
    NumericTraits<double>::max() );
  itkSetClampMacro( FixedImageStandardDeviation, double, 0.0,
    NumericTraits<double>::max() );

  /** Set the number of spatial samples. */
  itkSetClampMacro( NumberOfSpatialSamples, unsigned short, 1,
    NumericTraits<unsigned short>::max() );

  /** Set the number of iterations per level. */
  itkSetMacro( NumberOfIterations, UnsignedIntArray );

  /** Set the learning rate per level. */
  itkSetMacro( LearningRates, DoubleArray );

  /** Set the initial transform parameters. */
  itkSetMacro( InitialParameters, ParametersType );

  /** Set the fixed and moving image shrink factors. */
  itkSetMacro( FixedImageShrinkFactors, ShrinkFactorsArray );
  itkSetMacro( MovingImageShrinkFactors, ShrinkFactorsArray );

  // Description:
  // Initialize the Registration using a matrix
  void InitializeRegistration(vtkMatrix4x4 *matrix);

  // ----------------------------------------------------------------------
  // Run the Registration
  // ----------------------------------------------------------------------

  /** Method to execute the registration. */
  virtual void Execute();

  /** Initialize registration at the start of new level. */
  void StartNewLevel();

  // ----------------------------------------------------------------------
  // Get Parameters/Results
  // ----------------------------------------------------------------------

  /** Get number of parameters. */
  unsigned long GetNumberOfParameters()
    { return m_Transform->GetNumberOfParameters(); }

  /** Get computed transform parameters. */
  const ParametersType& GetTransformParameters()
    { return m_Registration->GetLastTransformParameters(); }

  const ParametersType& GetInitialParameters()
    { return m_InitialParameters; }

  // Description:
  // Set the Matrix using the current results of the registration
  void ResultsToMatrix(vtkMatrix4x4 *matrix)
    { ParamToMatrix(this->GetTransformParameters(),matrix);}

  // Description:
  // Set the Matrix using the Parameters.
  // Note that m_Transform is updated with the parameters.
  // This is really only for testing purposes, do not use.
  void ParamToMatrix(const ParametersType &Param,
                     vtkMatrix4x4 *matrix);
  // Description:
  // Test the ParamToMatrix function
  // with the InitializeRegistration function
  void Test();

  // Description:
  // How good was the alignment
  double GetMetricValue()
    {return m_Metric->GetValue(this->GetTransformParameters());}

  // Information to form K-L histogram
  typedef MetricType::HistogramType            HistogramType;
  typedef MetricType::HistogramSizeType        SizeType;

  // Description:
  // Either set all the images and transform and interpolator, or
  // just set the histogram
  MovingImageType *SetTrainingMovingImage( const MovingImageType *TrainingMovingImage )
    { m_Metric->SetTrainingMovingImage(TrainingMovingImage); }
  FixedImageType *SetTrainingFixedImage(  const FixedImageType  *TrainingFixedImage )
    { m_Metric->SetTrainingFixedImage(TrainingFixedImage); }
  void SetTrainingTransform(   const AffineTransformType::Pointer TrainingTransform )
    { m_Metric->SetTrainingTransform(TrainingTransform); }
  void SetTrainingInterpolator( const InterpolatorType::Pointer TrainingInterpolator )
    { m_Metric->SetTrainingInterpolator(TrainingInterpolator); }
  void SetHistogram( const HistogramType TrainingHistogram )
    { m_Metric->SetTrainingHistogram(TrainingHistogram); }

    // Description:
    // Set the size of the histogram for the metric
    // Default is 32 by 32
  void SetHistogramSize( const SizeType histSize )
    { m_Metric->SetHistogramSize(histSize); }

    // Description:
    // Set the histogram frequency to use if the frequency is 0
  void SetHistogramEpsilon( const double Epsilon) 
    { m_Metric->SetEpsilon(Epsilon);  }


protected:
  KLRegistration();
  ~KLRegistration();

  // Description:
  // Print everything
  virtual void PrintSelf(std::ostream& os, Indent indent) const;

private:
  KLRegistration( const Self& ); //purposely not implemented
  void operator=( const Self& ); //purposely not implemented

  typename FixedImageType::Pointer            m_FixedImage;
  typename MovingImageType::Pointer           m_MovingImage;
  typename TransformType::Pointer             m_Transform;
  typename InterpolatorType::Pointer          m_Interpolator;

  typename OptimizerType::Pointer             m_Optimizer;
  typename MetricType::Pointer                m_Metric;
  typename FixedImagePyramidType::Pointer     m_FixedImagePyramid;
  typename MovingImagePyramidType::Pointer    m_MovingImagePyramid;
  typename RegistrationType::Pointer          m_Registration;

  unsigned short                       m_NumberOfLevels;
  double                               m_TranslationScale;
  unsigned short                       m_NumberOfSpatialSamples;

  double                               m_MovingImageStandardDeviation;
  double                               m_FixedImageStandardDeviation;
                   
  UnsignedIntArray                     m_NumberOfIterations;
  DoubleArray                          m_LearningRates;
                   
  ShrinkFactorsArray                   m_MovingImageShrinkFactors;
  ShrinkFactorsArray                   m_FixedImageShrinkFactors;

  ParametersType                       m_InitialParameters;

  unsigned long                        m_ObserverTag;
  unsigned long                        m_OptimizeObserverTag;
};

} // namespace itk

#ifndef ITK_MANUAL_INSTANTIATION
#include "KLRegistration.txx"
#endif

#endif
