#! /bin/csh -f

### Set the directory in which your slicer is installed
if (${?SLICER_HOME} == 0) then
    setenv SLICER_HOME /projects/birn/pieper/slicer2/slicer2
endif

if (${?LD_LIBRARY_PATH} == 0) then
    setenv LD_LIBRARY_PATH " "
endif

### Set the library path to look in the build that you created
setenv LD_LIBRARY_PATH ${SLICER_HOME}/Base/builds/solaris8/bin:${LD_LIBRARY_PATH}

setenv TCL_LIBRARY /local/os/lib/tcl8.3
setenv TK_LIBRARY /local/os/lib/tk8.3

#### Set the Tcl Lib Path to look in VTK_HOME/Wrapping/Tcl

if (${?TCLLIBPATH} == 0) then
    setenv TCLLIBPATH " "
endif

setenv VTK_SRC_DIR /usr/local/src/vtk4/VTK/Wrapping/Tcl
setenv TCLLIBPATH "${SLICER_HOME}/Base/Wrapping/Tcl/vtkSlicerBase /usr/local/src/vtk4/VTK/Wrapping/Tcl ${TCLLIBPATH}"

setenv SLICER_LOCAL 0

echo TCL_LIBRARY  is $TCL_LIBRARY
echo TK_LIBRARY  is $TK_LIBRARY
echo SLICER_HOME  is $SLICER_HOME
echo DISPLAY      is $DISPLAY
echo LD_LIBRARY_PATH is $LD_LIBRARY_PATH
echo SLICER_LOCAL is $SLICER_LOCAL

exec /local/os/src/vtk-4.0/bin/vtk $SLICER_HOME/Base/tcl/Go.tcl $*
