#! /bin/csh -f

if (${?SLICER_HOME} == 0) then
    setenv SLICER_HOME /export/bigsur/slicer
endif

if (${?LD_LIBRARY_PATH} == 0) then
    setenv LD_LIBRARY_PATH ${SLICER_HOME}/lib:/local/lib
else
    setenv LD_LIBRARY_PATH ${SLICER_HOME}/lib:/local/lib:${LD_LIBRARY_PATH}
endif

if (${?DISPLAY} == 0) then
    setenv DISPLAY `${SLICER_HOME}/program/bin/finddisplay`
endif
setenv FINDDISPLAY `${SLICER_HOME}/program/bin/finddisplay`

setenv ANAPI_DATADICT ${SLICER_HOME}/program/bin/datadict

setenv TCL_LIBRARY ${SLICER_HOME}/lib/tcl8.3
setenv TK_LIBRARY ${SLICER_HOME}/lib/tk8.3
 
setenv VTK_RENDERER OpenGL

setenv SLICER_LOCAL 0

echo TCL_LIBRARY  is $TCL_LIBRARY
echo TK_LIBRARY  is $TK_LIBRARY
echo SLICER_HOME  is $SLICER_HOME
echo DISPLAY      is $DISPLAY
echo LD_LIBRARY_PATH is $LD_LIBRARY_PATH
echo SLICER_LOCAL is $SLICER_LOCAL
exec $SLICER_HOME/program/vtk $SLICER_HOME/program/Go.tcl $1
