#! /bin/csh -f
# Test Function for vtkImageEMLocalSegment - all environment variables are automatically set 
rm TestImageEMLocalSegmentTestResult.*

# Check if we have to source environment 
if (${?OS} == 0) then
    setenv OS $OSTYPE
endif

if ((${?VTK_EXE} == 0) && ($OS !=  Windows_NT)) then
  echo "sourcing setEnvironment .... "  
  source ../scripts/setEnvironment
endif

if (${?LD_LIBRARY_SLICER} != 0) then
    setenv LD_LIBRARY_PATH $LD_LIBRARY_SLICER
endif
if (${?TCLLIBPATH_SLICER} != 0) then
   setenv TCLLIBPATH "$TCLLIBPATH_SLICER"
endif
if (${?VTK_EXE} != 0) then
  ${VTK_EXE} TestImageEMPrivateSegment.tcl $*
else
  echo "Error: Before running this command execute the following command once:"
  echo "source ../scripts/setEnvironment" 
endif


