/* 
 * Here is where system computed values get stored.
 * These values should only change when the target compile platform changes.
 */

#cmakedefine VTKMUTUALINFORMATIONREGISTRATION_BUILD_SHARED_LIBS
#ifndef VTKMUTUALINFORMATIONREGISTRATION_BUILD_SHARED_LIBS
#define VTKMUTUALINFORMATIONREGISTRATION_STATIC
#endif

#if defined(WIN32) && !defined(VTKMUTUALINFORMATIONREGISTRATION_STATIC)
#pragma warning ( disable : 4275 )

#if defined(vtkMutualInformationRegistration_EXPORTS)
#define VTK_MUTUALINFORMATIONREGISTRATION_EXPORT __declspec( dllexport ) 
#else
#define VTK_MUTUALINFORMATIONREGISTRATION_EXPORT __declspec( dllimport ) 
#endif
#else
#define VTK_MUTUALINFORMATIONREGISTRATION_EXPORT
#endif
