#!/d/bigdaily/lauren/slicer/program/tclsh

foreach file "[glob -nocomplain *.tcl] [glob -nocomplain *.h] \
	[glob -nocomplain *.cxx]" {
	puts $file
	if {[catch {exec comment $file} errmsg] == 1} {
		puts $errmsg
		puts "Place the script 'comment' in the visible path and retry."
		exit
	}
}

