#! /bin/csh -f

###############################################################
# Run this script to automatically comment tcl files.
# Then fill in the comment headers.
# See slicer/program/Custom.tcl for an example of how to 
# fill in the headers.  
###############################################################

if (${?SLICER_HOME} == 0) then
    setenv SLICER_HOME /projects/birn/nicole/slicer2
endif

if (${?LD_LIBRARY_PATH} == 0) then
    setenv LD_LIBRARY_PATH ${SLICER_HOME}/Lib/solaris8:/local/lib
else
    setenv LD_LIBRARY_PATH ${SLICER_HOME}/Lib/solaris8/ActiveTcl-8.4.1/lib:/local/lib:${LD_LIBRARY_PATH}
endif

setenv TCL_LIBRARY ${SLICER_HOME}/Lib/solaris8/ActiveTcl-8.4.1/lib

# exec $SLICER_HOME/program/tclsh $SLICER_HOME/program/GoComment.tcl $1
exec ${SLICER_HOME}/Lib/solaris8/ActiveTcl-8.4.1/bin/tclsh $SLICER_HOME/Base/tcl/GoComment.tcl $1
