#! /bin/csh

setenv SLICER_HOME /export/bigsur/vtk/vtk3.0/slicer/slicer_12_99

setenv LD_LIBRARY_PATH ${SLICER_HOME}/lib:/local/lib:${LD_LIBRARY_PATH}
if (${?DISPLAY} == 0) then
	setenv DISPLAY `${SLICER_HOME}/program/bin/finddisplay`
endif
setenv TCL_LIBRARY ${SLICER_HOME}/lib/tcl8.2
setenv VTK_RENDERER OpenGL

echo TCL_LIBRARY  is $TCL_LIBRARY
echo SLICER_HOME  is $SLICER_HOME
echo DISPLAY      is $DISPLAY
echo LD_LIBRARY_PATH is $LD_LIBRARY_PATH

exec $SLICER_HOME/vtk $SLICER_HOME/program/printmrml.tcl $1 $2

