#! /bin/csh

# Usage: Copy this file to /d/bigdaily, and then run it.

echo Checkout into cvs directory
setenv CVSROOT /projects/cvs/slicer
mkdir cvs
mkdir slicer
cd cvs
cvs checkout slicer
cd ..

cd slicer

echo Copy the program directories
cp -r ../cvs/slicer/program .

echo Copy the doc directories
cp -r ../cvs/slicer/doc .

echo Copy tclsh
cp /local/share/src/tcl8.2.2/unix/tclsh program/bin

echo Copy tcl tcl binaries
mkdir lib
cp /local/share/src/tcl8.2.2/unix/libtcl8.2.so lib
cp /local/share/src/tk8.2.2/unix/libtk8.2.so lib

echo Copy tcl library directorys
cp -r /local/share/src/tcl8.2.2/library lib/tcl8.2
cp -r /local/share/src/tk8.2.2/library lib/tk8.2

echo Copy vtk binaries
cp /local/src/vtk3.01/common/*.so lib
cp /local/src/vtk3.01/graphics/*.so lib
cp /local/src/vtk3.01/imaging/*.so lib
cp /local/src/vtk3.01/patented/*.so lib
cp /local/src/vtk3.01/local/*.so lib

echo Copy vtk executable
cp /local/src/vtk3.01/tcl/vtk .

echo Copy the VTK Sources
cp -r ../cvs/slicer/vtksrc slicer/vtksrc

echo Finished
echo NOT, just change SLICER_HOME when you install. 

